### ISSUE TITLE
SubscribeToMarketDepthUpdates failed

### ISSUE THREAD

**Issue by mzhou2018** [JKorf/Huobi.Net#10]
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CryptoExchange.Net.Sockets.BaseSocket.<Close>b__72_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at CryptoExchange.Net.Sockets.BaseSocket.Close()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__75_5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at CryptoExchange.Net.Sockets.BaseSocket.Connect()
   at CryptoExchange.Net.SocketClient.ConnectSocket(SocketSubscription socketSubscription)
   at Huobi.Net.HuobiSocketClient.CreateAndConnectSocket[T](Boolean authenticate, Boolean sub, Action`1 onMessage) in K:\test\Huobi.Net\HuobiSocketClient.cs:line 630
   at Huobi.Net.HuobiSocketClient.Subscribe[T](HuobiRequest request, Action`1 onData) in K:\test\Huobi.Net\HuobiSocketClient.cs:line 447
   at Huobi.Net.HuobiSocketClient.SubscribeToMarketDepthUpdatesAsync(String symbol, Int32 mergeStep, Action`1 onData) in K:\test\Huobi.Net\HuobiSocketClient.cs:line 162
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Huobi.Net.HuobiSocketClient.SubscribeToMarketDepthUpdates(String symbol, Int32 mergeStep, Action`1 onData) in K:\test\Huobi.Net\HuobiSocketClient.cs:line 142
   at ConsoleApp1.OrderR.InitWSClient()
   at ConsoleApp1.OrderR.Run()
   at ConsoleApp1.Program.Main(String[] args)

**Comment by JKorf** [comment]
Hi, what version of Huobi.Net/CryptoExchange.Net do you use? Does this happen when trying to initially subscribe? `SubscribeToMarketDepthUpdates` works for me locally.
