### ISSUE TITLE
Api Access Error

### ISSUE THREAD

**Issue by kaveh6202** [JKorf/Huobi.Net#29]
I Get this error when i try to access authenticated endpoints.
Server error: api-signature-not-valid, Signature not valid: Incorrect Access key [Access key错误]
my Api Key and secret key is correct.

**Comment by JKorf** [comment]
Hi, no problems on my end. Do any authenticated calls work for you? Can you show how you configure/call the method? (don't forget to remove the actual key/secret)

**Comment by kaveh6202** [comment]
this is my constructor : 
_client = new HN.HuobiClient(new HN.HuobiClientOptions()
            {
                ApiCredentials = new ApiCredentials("Key", "Secret"),
                RateLimitingBehaviour = RateLimitingBehaviour.Wait,
                RequestTimeout = TimeSpan.FromSeconds(5)
            });

with this client initialized i get error in every GetAccount api . I can not call another endpoints though because i need to have this data first to fill another endpoint parameters

**Comment by JKorf** [comment]
Weird, no problems for me with that. Can you try generating a new key/secret to see if that works?

**Comment by PokerChang** [comment]
I tried many pairs of keys and get the same error:

(3) ➜  huobi_Python git:(master) ✗ python example/account/get_balance.py
Traceback (most recent call last):
  File "example/account/get_balance.py", line 10, in <module>
    list_obj = account_client.get_balance(account_id=g_account_id)
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/client/account.py", line 41, in get_balance
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/service/account/get_balance.py", line 24, in request
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/restapi_sync_client.py", line 116, in request_process
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/restapi_sync_client.py", line 121, in request_process_product
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/impl/restapi_invoker.py", line 67, in call_sync
  File "/Users/changluo/Documents/GitHub/huobi_Python/3/lib/python3.6/site-packages/huobi_client-2.0.0-py3.6.egg/huobi/connection/impl/restapi_invoker.py", line 30, in check_response
huobi.exception.huobi_api_exception.HuobiApiException: ('ExecuteError', '[Executing] api-signature-not-valid: Signature not valid: Incorrect Access key [Access key错误]')
