### ISSUE TITLE
Unhandled exception. System.ObjectDisposedException: The semaphore has been disposed.

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Huobi.Net#82]
Hi @JKorf ,
I got this exception. System.ObjectDisposedException in the the Huobi HuobiSpotSymbolOrderBook.
The exception stack is 
```
Unhandled exception. System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync()
   at CryptoExchange.Net.BaseSocketClient.QueryAsync[T](SocketApiClient apiClient, String url, Object request, Boolean authenticated)
   at Huobi.Net.Clients.SpotApi.HuobiSocketClientSpotStreams.GetOrderBookAsync(String symbol, Int32 levels)
   at Huobi.Net.SymbolOrderBooks.HuobiSpotSymbolOrderBook.DoResyncAsync(CancellationToken ct)
   at CryptoExchange.Net.OrderBook.SymbolOrderBook.ResyncAsync()
   at CryptoExchange.Net.OrderBook.SymbolOrderBook.<StartAsync>b__69_3(TimeSpan time)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

My analyze is that it is because while the resync occurs, I dispose of the OrderBook. In the HuobiHuobiSpotSymbolOrderBook. DoResyncAsync, the dispose occurs while the thread wait for 500 ms.

I am not certain what the correct solution is. 

Eric

**Comment by JKorf** [comment]
Hi Eric, I've done some improvements in the latest versions, let me know if you have any other issues
